Taisiia_project/app/models.py
from Taisiia_project.database import db
from sqlalchemy.orm import Mapped, mapped_column


class  Product(db.Model):
    __tablename__ = 'products'

    id: Mapped[int] = mapped_column(primary_key=True)
    product: Mapped[str]
    brand: Mapped[str | int]
    color: Mapped[str]
    description: Mapped[str | None]

    def __str__(self):
        return f'{self.id} {self.product} brand:{self.brand}, color:{self.color}'

Taisiia_project/app/forms.py
from flask_wtf import FlaskForm
from wtforms.fields.simple import SubmitField, StringField, TextAreaField
from wtforms.validators import DataRequired


class ShoppingForm(FlaskForm):
    title = None
    product = StringField('Product name', validators=[DataRequired()])
    brand = StringField('Brand name', validators=[DataRequired()])
    color = StringField('Color name', validators=[DataRequired()])
    description = TextAreaField('Description')
    submit = SubmitField('Submit')

Taisiia_project/app/__init__.py
import secrets

from flask import Flask
from flask_migrate import Migrate
from flask_wtf.csrf import CSRFProtect

from Taisiia_project.app.views import shopping_bp, main_bp
from Taisiia_project.database import db


def create_app():
    app = Flask(__name__)

    app.jinja_env.add_extension("jinja2.ext-do")
    app.config.from_mapping(
        SECRET_KEY=secrets.token_hex(64),
        SQLALCHEMY_DATABASE_URI="sqlite:///library.db",
        SQLALCHEMY_TRACK_MODIFICATIONS=False,
    )

    app.register_blueprint(shopping_bp)
    #app.register_blueprint(products_bp)
    #app.register_blueprint(brands_bp)
    #app.register_blueprint(colors_bp)
    app.register_blueprint(main_bp)

    db.init_app(app)
    Migrate(app, db)
    CSRFProtect(app)

    return app

Taisiia_project/app/views/__init__.py
from .shopping_list import shopping_bp
from .main import main_bp


__all__ = [
    "shopping_bp",
    "main_bp",
]

Taisiia_project/app/views/main.py
from flask import render_template, redirect, Blueprint, url_for

main_bp = Blueprint('main', __name__, url_prefix='/')


@main_bp.route("/")
def home():
    url_for("shopping.shopping_list")
    return redirect(url_for("shopping.shopping_list"))

@main_bp.route("/base")
def base():
    return render_template("base.html")

Taisiia_project/app/views/shopping_list.py
from flask import Blueprint
from flask import render_template, request, abort, redirect
from Taisiia_project.app.forms import ShoppingForm
from Taisiia_project.app.models import Product



shopping_bp = Blueprint('shopping_list', __name__, url_prefix='/shopping_list')

shopping_list = [
    {"id": 1, "product": "Sneakers", "brand": "Adidas", "color": "black"},
    {"id": 2, "product": "Jeans", "brand": "Levi's", "color": "blue"},
    {"id": 3, "product": "Loafers", "brand": "Reformation", "color": "black"},
    {"id": 4, "product": "Dress", "brand": "Zara", "color": "black"},
    {"id": 5, "product": "Long-Sleeve", "brand": "Everlane", "color": "gray"},
]

@shopping_bp.route("/")
def list_items():
    return render_template("shopping/list.html", shopping_list=shopping_list)

@shopping_bp.route("/<int:product_id>/")
def product_details(product_id):
     product = get_item_by_id(product_id)
     return render_template("shopping/list.html", shopping_list=[product])

@shopping_bp.route("/add/", methods=["GET", "POST"])
def create_product():
    shopping_form = ShoppingForm()
    if request.method == "POST" and shopping_form.validate_on_submit():
        product = shopping_form.product.data
        brand = shopping_form.brand.data
        color = shopping_form.color.data
        description = shopping_form.description.data
        shopping_list.append({"id": len(shopping_list) + 1, "product": product, "brand": brand, "color": color, "description": description})
        return redirect("/shopping-list")
    return render_template("shopping/add", shopping_form=shopping_form)

@shopping_bp.route("/<int:product_id>/edit/", methods=["GET", "POST"])
def edit_product(product_id):
    product = get_item_by_id(product_id)
    shopping_form = ShoppingForm(data=product)
    if request.method == "POST" and shopping_form.validate_on_submit():
        product["product"] = shopping_form.product.data
        product["brand"] = shopping_form.brand.data
        product["color"] = shopping_form.color.data
        product["description"] = shopping_form.description.data
        return redirect("/shopping-list")
    return render_template("shopping/edit.html", shopping_form=shopping_form)

@shopping_bp.route("/<int:product_id>/delete/", methods=["GET", "POST"])
def delete_product(product_id):
    product = get_item_by_id(product_id)
    shopping_list.remove(product)
    return redirect("/shopping-list")


def get_item_by_id(product_id):
    for product in shopping_list:
        if product["id"] == product_id:
            return product
    abort(404)

def add_product():
    return render_template("shopping/add.html")

Taisiia_project/app/templates/elements/base.html
<!DOCTYPE html>
<html lang="uk">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Shopping guide{% endblock %}</title>
  <!-- Підключення Bootstrap CSS -->
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
    crossorigin="anonymous">
  <style>
      {% block styles %}{% endblock %}
  </style>
</head>
<body>

<header>
    {% block header %}
    {% include "menu.html" %}
    {% endblock %}
</header>

  <!-- Основний контент -->
<main class="container my-5">
    {% block main %}
    <div class="text-center">
      <h1 class="mb-4">Ласкаво просимо!</h1>
      <p class="lead">Це базовий шаблон сторінки з підключеним Bootstrap 5.</p>
      <a href="#" class="btn btn-primary btn-lg">Дізнатися більше</a>
    </div>
    {% endblock %}
</main>

  <!-- Підвал -->
<footer>
  {% include "footer.html" %}
</footer>

  <!-- Підключення Bootstrap JS -->
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
  <script>
      {%block scripts %}{% endblock %}
  </script>
</body>
</html>

Taisiia_project/app/templates/elements/footer.html
<footer class="bg-light text-center text-md-start py-4 border-top">
  {% block footer %}
  <div class="container">
    <div class="row">
      <!-- About -->
      <div class="col-md-8 mb-3">
        <h5>About us</h5>
        <p>
          Welcome to <strong>ShoppingHelper</strong> — your personal assistant for smarter shopping!<br>
          We help you save time, money, and energy by finding the best products, comparing prices,
          and sharing practical shopping tips.<br>
          Our mission is simple — make your shopping experience easier, faster, and more enjoyable.
        </p>
      </div>

      <!-- Contact -->
      <div class="col-md-4 mb-3">
        <h5>Contact us</h5>
        <address>
          <p><i class="bi bi-envelope-fill me-2"></i>Email: support@yourwebsite.com</p>
          <p><i class="bi bi-telephone-fill me-2"></i>Phone: +1 (234) 567-890</p>
        </address>
      </div>
    </div>

    <hr>
    <p class="mb-0 text-center">&copy; 2025 Мій сайт. Всі права захищено.</p>
  </div>
  {% endblock %}
</footer>

Taisiia_project/app/templates/elements/macro.html
{% macro render_form_elementsform) %}
    {% for field in form %}
        {{ render_field(field) }}
    {% endfor %}
{% endmacro%}

{% macro render_field(field), input_args=None %}
    {% set  input_args = dict() if input_args == None else input_args %}

    {%set render_map = {
        "SubmitField": render_submit_button,
        "CSRFTokenField: render_csrf_token_field,
        "default": render_regular_field,
    } %}

    {% set field_type = field.type if field.type in render_map else "default" %}
    {{render_map[field_type](field, input_args) }}
{% endmacro %}


{% macro render_submit_button(field, input_args) %}
    {{ field(class="btn btn-dark") }}
{% endmacro %}


{% macro render_csrf_token_field(field;input_args) %}
{{ fieldo () }}
{% endmacro %}


{% macro render_regular_field(field, input_args) %}
    {% do set_class_ars(field,  input_args) %}

    <div class="mb-3">
        {{ field.label(class="form-label") }}
        {{ field(**input_args) }}
        {{ render_field_errors(field.errors) }}
    </div>
{% endmacro %}


{% macro set_class_args(field, input_args) %}
    {% set classes = "form-control" %}
    {% if field.errors %}
        {% set classes = classes + " is-invalid" %}
    {% endif %}
    {% if "class" in input_args %}
        {% set classes = classes + " " + input_args["class"] %}
    {% endif %}
    {% do input_args.update({"calss": classes}) %}
{% endmacro %}


{% marco render_field_errore(errors) %}
    {% for error in errors %}
        <div class="text-danger">{{ error }}</div>
    {% endfor %}
{% endmarco %}


{% marco render_flash_messages(errors) %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for message_category, message in messages %}
                {% set alert_type = get_alert_type(message_category) | trim %}
                <div class="alert alert-{{ alert_type }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
{% endmarco %}

{% macro get_alert_type(message_category) %}
    {% if message_category == "message" %}
        {{ "info" }}
    {% else %}
        {{ message_category }}
    {% endif %}
{% endmacro %}

Taisiia_project/app/templates/elements/menu.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="navbar-brand"
             href="{{ url_for('main.home') }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {{ 'active' if request.endpoint == 'tips.tips_list' }}" href="{{ url_for('tips.tips_list') }}">Tips</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {{ 'active' if request.endpoint == 'outfits.outfits_list' }}" href="{{ url_for('outfits.outfits_list') }}">Outfits</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {{ 'active' if request.endpoint == 'trends.trends_list' }}" href="{{ url_for('trends.trends_list') }}">Trends</a>
        <li class="nav-item">
          <a class="nav-link {{ 'active' if request.endpoint == 'shopping_list.shopping_list' }}" href="{{ url_for('shopping_list.shopping_list') }}">Shopping List</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

Taisiia_project/app/templates/shopping/add.html
{% from "macro.html" import render_form_elements with context %}
{% extends "base.html" %}

{% block title %}Shopping Helper - Add neu product{% endblock %}

{% block content %}
    <h1 class="mb-4">Add product</h1>

    <form method="POST" novalidate>
      {{ render_form_elements(product_form) }}
    </form>

{% endblock content %}

Taisiia_project/app/templates/shopping/edit.html
{% from "macro.html" import render_form_elements with context %}
{% extends "base.html" %}

{% block title %}Shopping Helper - Edit product{% endblock %}

{% block content %}
    <h1 class="mb-4">Edit product</h1>

    <form method="POST" novalidate>
      {{ render_form_elements(product_form) }}
    </form>

{% endblock content %}

Taisiia_project/app/templates/shopping/list.html
{% extends "base.html" %}

{% block title %}Shopping Helper{% endblock title %}

{% block content %}
    <h1 class="mb-4">Shopping List</h1>
    {{ "<b>Hi</b> | safe }}
    {{ "<b>Hi</b> }}
    <div class="list-group">
        <table class="table table-light">
            <thead>
            <tr class="table-light">
                <th scope="col">#</th>
                <th scope="col">Product Type</th>
                <th scope="col">Brand</th>
                <th scope="col">Color</th>
                <th scope="col">Details</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
            </thead>
            <tbody>
            {% for product in shopping_list %}
                <tr>
                    <th scope="row">{{ product.id }}</th>
                    <td>{{ product.product }}</td>
                    <td>{{ product.brand }}</td>
                    <td>{{ product.color }}</td>
                    <td><a href="{{ url_for('shopping_list.product_details', product_id=product.id) }}"
                        class="btn btn-secondary">Details</a></td>
                    <td><a href="{{ url_for('shopping_list.edit_product', product_id=product.id) }}"
                        class="btn btn-dark">Edit</a></td>
                    <td>
                        <form action="{{ url_for('shopping_list.delete_product', product_id=product.id) }}" method="POST">
                              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                              <button type="submit" class="btn btn-danger"
                                    onclick="return confirm('Do you really want to delete {{ shopping_list.product }}?'">Delete</button>
                        </form></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <a href="{{ url_for('add_product') }}" class="btn btn-link mt-4">Add product</a>
{% endblock content %}
    